### PR TITLE
Add Python 2 for building node10

### PR DESCRIPTION
**Pull request by gasinvein**
For flathub/flathub#1004

### CODE REVIEW

**Comment by refi64** [comment]
Thanks for this! However, I ended up using shared-modules's Python 2 instead, which was very similar to this but with some extra cleanup handled ~~and then maintaining that part won't be my problem~~

**Comment by refi64** [comment]
Actually dangit I see why you added this manually, the cleanup command in shared-modules is wrong for this case.

**Comment by gasinvein** [comment]
Yeah, python2 from shared-modules cleans up too much, some of those things may be required for building node-gyp binary modules or something.
Also it's better to build python2 statically, otherwise one would need to add libpython.so to ld-path.

**Comment by refi64** [comment]
Ugh indeed you're right, the ld paths are going to be an issue.

**Pull request closed without merging**
